### ISSUE TITLE
Can't see the example lessons in the lesson selector

### ISSUE THREAD

**Issue by jdlom** [boundlessgeo/qgis-lessons-plugin#3]
Hi,
I have all lessons plugin active :
- Lessons Plugin
- LessonsCreator
- Lessons (examplelessons)

Unfortunately, I can't see the example lessons in the lesson selector.
I have put the 3 folders (lessons, lessonscreator, exampleslessons) in the qgis/plugins folder and I have actived them in the plugin manager. 
I am running qgis 2.16.3 on windows 7.

Best regards,

**Comment by alexbruy** [comment]
Are there any messages in the QGIS log?

**Comment by jdlom** [comment]
Sorry, I have omited the --recursive flag during the installation. By doing the installation properly, it fixes the problem.  It would be great to diffuse the plugin on the official repository ?
